server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ventas/ {
        proxy_pass http://a55ec6ee47c564a4bbf5ad09294c33c3-1892273342.us-east-1.elb.amazonaws.com/api/ventas/;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 10s;
        proxy_read_timeout 30s;
    }

    location /api/despachos/ {
        proxy_pass http://ada3fe0faae934e30a1df9a586414e5f-1222427662.us-east-1.elb.amazonaws.com/api/despachos/;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 10s;
        proxy_read_timeout 30s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    server_tokens off;
}
