services:
  frontend:
    image: ${DOCKER_USERNAME}/innovatech-frontend:latest  # ← esto permite docker compose pull
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: innovatech_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - frontend_net

networks:
  frontend_net:
    name: innovatech_frontend_net
    driver: bridge