script: |
            cd ~/Innovatech_Frontend

            git remote set-url origin https://github.com/MatiDroid21/Innovatech_Frontend.git

            git pull origin deploy

            cat > .env <<EOF
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            EOF

            docker compose pull
            docker compose up -d --remove-orphans

            docker image prune -f